# Change these first
owner: isle-project # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ISLE Documentation
    url: https://isledocs.com
  - name: CMU Heinz College ISLE Instance
    url: https://isle.heinz.cmu.edu/ping
  - name: Kymetis ISLE Instance
    url: https://isle.kymetis.com/ping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isledocs.com
  logoUrl: https://raw.githubusercontent.com/isle-project/www/master/images/isle_icon_transparent.png
  name: ISLE Instances
  introTitle: "ISLE Uptime and Status Page"
  introMessage: Current uptime and status of public instances.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees: # Users to assign downtime issues (optional)
  - Planeshifter
