# Change these first
owner: isle-project # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ISLE Documentation
    url: https://isledocs.com
    icon: https://isledocs.com/img/favicon.png
  - name: ISLE Website
    url: https://stat.cmu.edu/isle
    __dangerous__insecure: true
    icon: https://isledocs.com/img/favicon.png
  - name: CMU Statistics & Data Science ISLE Instance
    url: https://isle.stat.cmu.edu/ping
    __dangerous__insecure: true
    icon: https://www.stat.cmu.edu/favicon.ico
  - name: CMU Heinz College ISLE Instance
    url: https://isle.heinz.cmu.edu/ping
    icon: https://www.heinz.cmu.edu/heinz-shared/_files/favicon.ico
  - name: Kymetis ISLE Instance
    url: https://isle.kymetis.com/ping
    icon: https://kymetis.com/favicon.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isledocs.com
  logoUrl: https://raw.githubusercontent.com/isle-project/www/master/images/isle_icon_transparent.png
  themeUrl: https://raw.githubusercontent.com/isle-project/status/master/assets/isle-theme.css
  name: ISLE Instances
  introTitle: "ISLE Uptime and Status Page"
  introMessage: Current uptime and status of public instances.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *" # Run the workflow every day at midnight
  responseTime: "0 23 * * *" # Run every day at 23:00
  staticSite: "0 1 * * *" # Generate the static site every day at 01:00
  summary: "0 0 * * *" # Generate the summary every day at midnight
  updateTemplate: "0 0 * * *" # Update the template every day at midnight
  updates: "0 3 * * *" # Update the status every day at 03:00
  uptime: "*/30 * * * *" # Update the uptime every 30 minutes

assignees: # Users to assign downtime issues (optional)
  - Planeshifter
